[package]
name = "dividend-contract"
version = "0.1.0"
edition = "2021"

[dependencies]
soroban-sdk = { version = "22" }
chrono = { version = "0.4" }

[dev-dependencies]
soroban-sdk = { version = "22", features = ["testutils"] }
